### PR TITLE
full emoji (unicode-10.0) support + asian language support

### PR DESCRIPTION
**Pull request by AubreyHewes**
This was complicated.. though this adds support for unicode emoji (via `Symbola`) up to version 10 (current) and asian unicode glyphs

 * Changes base electron to 1.7.9
 * Changes base node to v8 (Dockerfile, package-engine, wercker-box) 
 * Changes base image to `debian:stretch-slim`
   * previous base image included some stuff (curl); now this does it (breaks from upstream)
 * To support emoji at the latest version (https://emojipedia.org/unicode-10.0/) it was required to _include_ an own font (`ubuntu:artful` seems to have it `debian:stretch` does not)... stretch only has unicode 9 https://emojipedia.org/unicode-9.0/ 
 *  Support for Asian languages (Japanese, Chinese & Korean) it was required to add the fonts to the `Dockerfile` (could still be incomplete)
 *  Support for Ancient languages it was required to add the fonts to the `Dockerfile`

I am still not completely assured that this will support _all_ requirements.. though is now better ;-)

TODO Language support (Check)

 *  Support for Arabic
 *  Support for Hebrew

TODO

 * Seperate and PR to upstream (upstream may not want support for non latin languages)

### CODE REVIEW

**Comment by fruitl00p** [comment]
should we update the fork before pulling this in? Seems like upstream fixed several things aswell? (newer electron et al)

**Comment by AubreyHewes** [comment]
This encompasses the upstream changes.. electron version et al..  though upstream still has the problem of missing unicode support ;-)  

The major problems are the missing font/unicode support.

This can get us up and running again.. then we need to split this project for upstream-fork and own added support..

**Comment by fruitl00p** [comment]
Or make the PR smaller by merging upstream first? :)

**Comment by AubreyHewes** [comment]
hmmz.. Though the PR would be the same, only the diff would be different ;-)

**Comment by AubreyHewes** [comment]
I will get to it anyway.. ;-)

**Comment by AubreyHewes** [comment]
PR is much bigger as this squashed stuff see #2

**Pull request closed without merging**
